export const historyItems = [
  {
    title: "Senior Software Developer",
    description: [
      "Worked as a Senior Software Developer in Anyhau's development team.",
      "Executed the project with several different methodologies, gaining insights into the local markets of Finland and Northern Europe.",
      "Gained experience in the scales and objectives of Finnish ventures.",
      "Developed a pet reservation system and application related to service providers, which now stands in my portfolio.",
      "Worked extensively with NextJs, Vercel, i18next, SSG, and MongoDb.",
      "Participated in valuable meetings with teams from brands like VivaWallet, Vercel, and MongoDB, gaining insider insights.",
    ],
    dateStart: "May 2023",
    dateEnd: "Aug 2023",
    role: "Senior Software Developer",
    company: {
      name: "Anyhau",
      icon: "anyhau.png",
      website: "https://www.anyhau.fi",
    },
    stack: [
      "NextJs",
      "Vercel",
      "i18next",
      "SSG",
      "MongoDb",
      "React",
      "Software Architecture",
    ],
  },
  {
    title: "Full Stack Developer",
    description: [
      "Contributed to the development of CRM and ERP applications at ALFATEK Software Consulting Ltd.",
      "Used PHP, Vue, and NodeJs in these projects.",
      "Participated in various aspects of a marketplace project for the Australian market and developed a tool to simplify the use of the i18n library in PHP.",
      "Worked with various new libraries and tools and created reusable libraries and tools for PHP and Javascript.",
      "Developed WebSocket, multi-channel notifications, and chat applications.",
      "Played a role in integrating and enhancing existing applications.",
      "Gained experience in e-commerce panels, payment pools, payment channels.",
    ],
    dateStart: "Nov 2021",
    dateEnd: "Nov 2022",
    role: "Full Stack Developer",
    company: {
      name: "ALFATEK Software Consulting Ltd.",
      icon: "alfatek.png",
      website: "https://alfatekyazilim.com.tr/",
    },
    stack: ["PHP", "Vue", "NodeJs", "i18n", "WebSocket", "E-commerce"],
  },
  {
    title: "Lead Software Developer",
    description: [
      "Served as a Lead Software Developer at MT Medya, a media agency, overseeing web and mobile projects with a team of three colleagues.",
      "Revised the company's portfolio site for continuity and implemented necessary improvements.",
      "Developed an online course panel with Laravel and PHP, completing a complex project in the company's portfolio.",
      "Made improvements to sales channels, developed cross-platform applications, and advanced control panels for the company portfolio.",
      "Prototyped small-scale 3D game projects with Unity and C#, providing a customer with an opportunity to complete a sale.",
      "Facilitated coordination and communication within a team with diverse languages and cultures.",
      "Involved in orienting junior developers.",
    ],
    dateStart: "Nov 2020",
    dateEnd: "Oct 2021",
    role: "Lead Software Developer",
    company: {
      name: "MT Medya",
      icon: "mtmedya.png",
      website: "https://mtmedyaajans.com.tr/",
    },
    stack: ["Laravel", "PHP", "Unity", "C#", "E-commerce"],
  },
  {
    title: "Lead Software Developer",
    description: [
      "Managed software and development processes with the team in which two of my colleagues took part in the company serving as a web design agency.",
      "Developed CRM and ERP projects for the company and made many suggestions to improve business follow-up in other departments of the company.",
      "Improved the communication of development and sales departments by optimizing the processes of sales channels that are not used effectively.",
      "Developed tools that made project follow-up and sales processes 50% less time-consuming for the company and ensured that these were permanent in the company culture.",
      "Developed a boilerplate with PHP and Laravel for use in small-scale corporate websites and eliminated repetitive processes in new projects.",
      "Provided the connections of the cloud answering machine, which I took an active role in the installation processes for use in the company's products, with the integration of ERP and CRM I developed.",
      "Developed a news website project for the second brand of the company and took the lead in marketing the panels I developed to local news organizations.",
    ],
    dateStart: "Sep 2019",
    dateEnd: "Aug 2020",
    role: "Lead Software Developer",
    company: {
      name: "Medya Mavi",
      icon: "medyamavi.png",
      website: "https://medyamavi.com.tr/",
    },
    stack: [
      "PHP",
      "Laravel",
      "Swift",
      "VueJs",
      "NodeJs",
      "Web Design",
      "CRM",
      "ERP",
    ],
  },
  {
    title: "Application Developer",
    description: [
      "Ported the native android application, which was created with the integration software of the company using the netsis infrastructure, to the iOs environment with xamarin and ionic/angular technologies.",
      "Developing an existing application in a different working environment with the technologies I have just learned gave me a very useful perspective.",
      "Learned new working styles by keeping in touch with backend developers and developing with the ever-evolving API.",
      "Had the opportunity to examine the processes by which the planning, creation, and development of products is managed. Gained my developer self-confidence, which gave impetus to my individual projects.",
      "Had the opportunity to work with valuable and competent seniors and gained valuable experience not only about the technologies I was interested in, but also about IOT and embedded systems.",
      "Gained valuable experience about business life and corporate life. Learned professional patience and how to soften the slopes of learning processes.",
    ],
    dateStart: "Jan 2018",
    dateEnd: "Nov 2018",
    role: "Application Developer",
    company: {
      name: "Bracket Teknoloji",
      icon: "bracket.png",
      website: "https://www.bracket.com.tr/",
    },
    stack: [
      "Android",
      "iOS",
      "Xamarin",
      "Ionic",
      "Angular",
      "API",
      "IOT",
      "Embedded Systems",
    ],
  },
  {
    title: "Application Developer",
    description: [
      "Trained myself in mobile application development in the team where I started to work as a junior.",
      "Developed the iOs and Android applications of the company's web projects as native.",
      "Gained experience on dorm listing platforms and company listing platforms.",
      "Developed a casual mobile game for Android with Unity3D.",
      "Completed revisional tasks in the company's CRM software developed with PHP and gained experience with scalable projects.",
    ],
    dateStart: "Jul 2017",
    dateEnd: "Dec 2017",
    role: "Application Developer",
    company: {
      name: "Proweb",
      icon: "proweb.svg",
      website: "https://www.proweb.com.tr/tr/",
    },
    stack: [
      "iOS",
      "Android",
      "Unity3D",
      "PHP",
      "CRM",
      "Mobile Application Development",
    ],
  },
];
